permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 杨旗
  email: 531905408@qq.com
  link: #http://yansu.org
  weibo: #http://weibo.com/yansu0711
  github: http://github.com/mmmy

# 站点信息
title: 杨旗的博客 
description: 杨旗的博客
url: #http://yansu.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xkr9q.com1.z0.glb.clouddn.com/avatar.jpg
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: #UA-54767140-1
  url: #yansu.org

# disqus 设置
disqus:
  shortname: #suyan-zh